const STOP_WORDS = new Set([
    'a',
    'an',
    'and',
    'are',
    'as',
    'at',
    'be',
    'by',
    'for',
    'from',
    'has',
    'he',
    'in',
    'is',
    'it',
    'its',
    'of',
    'on',
    'that',
    'the',
    'to',
    'was',
    'were',
    'will',
    'with',
    'you',
    'your',
    'our',
    'we',
    'or',
    'but',
    'not',
    'this',
    'these',
    'those',
    'their',
    'they',
    'them',
    'can',
    'could',
    'should',
    'would',
    'must',
    'about',
    'into',
    'over',
    'after',
    'before',
    'than',
    'then',
    'also',
    'using',
    'used',
    'within',
    'across',
    'through',
]);

const ATS_PRIORITY_KEYWORDS = [
    'javascript',
    'typescript',
    'react',
    'node',
    'express',
    'mongodb',
    'sql',
    'python',
    'java',
    'aws',
    'azure',
    'docker',
    'kubernetes',
    'rest api',
    'microservices',
    'ci cd',
    'git',
    'agile',
    'scrum',
    'leadership',
    'stakeholder management',
    'data analysis',
    'machine learning',
    'nlp',
    'automation',
    'testing',
    'unit testing',
    'integration testing',
    'security',
    'scalability',
    'performance optimization',
    'problem solving',
    'communication',
    'project management',
];

const SECTION_HINTS = {
    summary: ['summary', 'profile', 'objective'],
    experience: ['experience', 'employment', 'work history'],
    skills: ['skills', 'technical skills', 'core competencies'],
    education: ['education', 'academic', 'qualification'],
    projects: ['projects', 'portfolio'],
};

module.exports = {
    STOP_WORDS,
    ATS_PRIORITY_KEYWORDS,
    SECTION_HINTS,
};
